### ISSUE TITLE
인혁님! my_page.py에러가 나서 한 번 올려봅니다!

### ISSUE THREAD

**Issue by ho-bolt** [Hanghae99Study/Hanghae99-ToyProject#22]
제가 인혁님이 어제 밤에 머지하신 코드를 fetch해서 제거 메인을 수정하려고 했는데 
**AssertionError: View function mapping is overwriting an existing endpoint function: my_page.correction_update**  이 에러가 뜹니다 
확인해보니 
@ 하나의 파이썬 파일에 동일한 이름의 함수가 선언되어서 그렇다고 뜹니다! 

fetch 해온 코드를 보니 **/correction_update가 2개가 있어서 그런 거 같은데** 한 번 확인부탁드립니다!

**Comment by Dplo1514** [comment]
넵!! 확인 감사합니다🙂🙏
오늘 퇴근하고 수정 후 재 업데이트 하도록 하겠습니다!!

**Comment by ho-bolt** [comment]
확인했습니다.

**Comment by Dplo1514** [comment]
감사합니다 호진님ㅋㅋㅋㅋㅋㅋㅋ
